packages:
- packages/*
- apps/*

ignoredBuiltDependencies:
- '@parcel/watcher'
- '@scarf/scarf'
- '@swc/core'
- core-js-pure
- esbuild
- nx

onlyBuiltDependencies:
- better-sqlite3
- electron
- electron-winstaller

nodeLinker: hoisted
linkWorkspacePackages: true
