packages:
  - packages/*
  - apps/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - better-sqlite3
  - bufferutil
  - core-js-pure
  - esbuild
  - nx
  - utf-8-validate

onlyBuiltDependencies:
  - electron
