packages:
- packages/*
- apps/*

ignoredBuiltDependencies:
- '@parcel/watcher'
- '@scarf/scarf'
- '@swc/core'
- bufferutil
- core-js-pure
- esbuild
- nx
- utf-8-validate

onlyBuiltDependencies:
- better-sqlite3
- electron
- electron-winstaller
- fs-xattr
- macos-alias

hoistPattern:
# Used by packages/ckeditor-* eslint script
- eslint-plugin-*
- eslint-plugin-ckeditor5-rules
- ckeditor5
- "@ckeditor/*"

nodeLinker: isolated
