packages:
- packages/*
- apps/*

ignoredBuiltDependencies:
- '@parcel/watcher'
- '@scarf/scarf'
- '@swc/core'
- bufferutil
- core-js-pure
- esbuild
- nx
- utf-8-validate

onlyBuiltDependencies:
- electron
- better-sqlite3
