name: Release to winget
on:
  workflow_call:
    inputs:
      release_tag:
        description: 'Git tag to release from'
        type: string
        required: true
    secrets:
      token:
        required: true
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Git tag to release from'
        type: string
        required: true
jobs:
  release-winget:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to WinGet
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: TriliumNext.Notes
          token: ${{ secrets.token }}
          release-tag:  ${{ github.event.inputs.release_tag }}
