name: Release to winget
on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Git tag to release from'
        required: true
jobs:
  release-winget:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to WinGet
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: TriliumNext.Notes
          token: ${{ secrets.WINGET_PAT }}
          release-tag:  ${{ github.event.inputs.release_tag }}
