name: Release
on:
    push:
jobs:
    publish-github-registry:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up node & dependencies
              uses: actions/setup-node@v4
              with:
                node-version: 20
                registry-url: https://npm.pkg.github.com/
                cache: "npm"
            - run: yarn install
            - run: yarn publish
              env:
                NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        permissions:
            packages: write
