name: Release
on:
    push:
        tags:
            - 'v*'
jobs:
    publish-github-registry:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: corepack enable
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn install
            - run: yarn push
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}